#!/usr/bin/env python3
""" 
This script has been generated by AI with minor tweaks from the author

This script converts a VHD image file to a HEX file (to initiate SRAM)
"""

import re
import sys
import os


def extract_hex_values(input_file, output_file):
    # Read the input file
    try:
        with open(input_file, 'r') as file:
            data = file.read()
    except IOError as e:
        print(f"Error reading {input_file}: {e}")
        sys.exit(1)

    # Regular expression to match hex values in the format x"xxxxxxxx"
    hex_values = re.findall(r'x"([0-9A-Fa-f]+)"', data)

    # Write the extracted hex values to the output file
    try:
        with open(output_file, 'w') as file:
            for hex_value in hex_values:
                file.write(f"{hex_value}\n")
    except IOError as e:
        print(f"Error writing to {output_file}: {e}")
        sys.exit(1)

    print(f"Extracted {len(hex_values)} hex values into {output_file}")


def main():
    # Check if the user provided the input file name.
    if len(sys.argv) != 2:
        print("Usage: python extract_hex.py <input_file>")
        sys.exit(1)

    input_file = sys.argv[1]

    # Extract the base name and use a .hex extension for the output file.
    base_name, _ = os.path.splitext(input_file)
    output_file = f"{base_name}.hex"

    extract_hex_values(input_file, output_file)


if __name__ == "__main__":
    main()
